stash-merritt/spec/db/datacite/mapping/datacite_xml_factory_spec.rb
stash-merritt/spec/db/stash/merritt/object_manifest_package_spec.rb
stash-merritt/spec/db/stash/merritt/repository_spec.rb
stash-merritt/spec/db/stash/merritt/sword_helper_spec.rb
stash-merritt/spec/db/stash/merritt/zip_package_spec.rb
stash_datacite/spec/db/stash_engine/resource_spec.rb
stash_engine/app/models/stash_engine/user.rb
stash_engine/db/migrate/20180713205424_simplify_login_fields.rb
stash_engine/spec/db/stash_engine/author_spec.rb
stash_engine/spec/db/stash_engine/file_upload_spec.rb
stash_engine/spec/db/stash_engine/resource_spec.rb

Remove unnecessary fields from the stash_engine_users table.
This must be performed in conjunction with https://github.com/CDL-Dryad/dryad/pull/4

Simplify login fields

---

stash_engine/db/migrate/20180814050258_add_eperson.rb

This is pretty self-explanatory.

Add eperson_id (from old Dryad) to stash_engine_users

---

stash_api/Gemfile
stash_api/Gemfile.lock
stash_api/app/assets/javascripts/stash_api/users.js
stash_api/app/assets/stylesheets/stash_api/users.css
stash_api/app/controllers/stash_api/application_controller.rb
stash_api/app/controllers/stash_api/datasets_controller.rb
stash_api/app/controllers/stash_api/users_controller.rb
stash_api/app/helpers/stash_api/users_helper.rb
stash_api/app/models/stash_api/dataset_parser.rb
stash_api/app/models/stash_api/user.rb
stash_api/app/models/stash_api/version.rb
stash_api/app/models/stash_api/version/metadata.rb
stash_api/config/routes.rb
stash_api/lib/core_extensions/hash/recursive_compact.rb
stash_api/spec/controllers/stash_api/users_controller_spec.rb
stash_api/spec/factories/stash_engine/identifiers.rb
stash_api/spec/factories/stash_engine/resource_states.rb
stash_api/spec/factories/stash_engine/resources.rb
stash_api/spec/factories/stash_engine/users.rb
stash_api/spec/factories/stash_engine/versions.rb
stash_api/spec/factory_helper.rb
stash_api/spec/helpers/stash_api/users_helper_spec.rb
stash_api/spec/internal/config/routes.rb
stash_api/spec/internal/db/schema.rb
stash_api/spec/rails_helper_unused.rb
stash_api/spec/spec_helper.rb
stash_api/spec/unit/models/stash_api/dataset_parser_spec.rb
stash_api/spec/unit/models/stash_api/dataset_spec.rb
stash_api/spec/unit/models/stash_api/user_spec.rb

This also has some of the "skip metadata update" API changes from an earlier pull request merged in.
For a bunch of info about what this does, see https://github.com/CDL-Dryad/dryad-product-roadmap/issues/86 .

This is the read-only user API for getting info about a user for superusers

---

stash_api/app/controllers/stash_api/datasets_controller.rb
stash_api/app/models/stash_api/dataset_parser.rb
stash_api/spec/unit/models/stash_api/dataset_parser_spec.rb

This is the PR for this ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/75 .

Able to set userId (for owner) if you're a superuser using the API

---

stash_api/app/controllers/stash_api/application_controller.rb
stash_api/app/controllers/stash_api/files_controller.rb
stash_api/app/controllers/stash_api/urls_controller.rb

This goes with https://github.com/CDL-Dryad/dryad-product-roadmap/issues/98 .  I've added some details of testing in there.

This allows for files to be deleted from a version

---

stash_api/app/models/stash_api/dataset_parser.rb
stash_api/app/models/stash_api/dataset_parser/temporal_coverages.rb
stash_api/app/models/stash_api/version/metadata.rb
stash_api/app/models/stash_api/version/metadata/temporal_coverages.rb
stash_datacite/app/controllers/stash_datacite/temporal_coverages_controller.rb
stash_datacite/app/models/stash_datacite/resource/completions.rb
stash_datacite/app/models/stash_datacite/resource/metadata_entry.rb
stash_datacite/app/models/stash_datacite/resource/review.rb
stash_datacite/app/models/stash_datacite/resource/schema_dataset.rb
stash_datacite/app/models/stash_datacite/temporal_coverage.rb
stash_datacite/config/routes.rb
stash_datacite/db/migrate/20181011020342_create_stash_datacite_temporal_coverages.rb
stash_datacite/lib/stash_datacite/resource_patch.rb
stash_datacite/spec/db/stash_datacite/temporal_coverage_spec.rb

This is probably not quite ready for merging, but I’d like to leave it available for @sfisher to look at and see if I’ve got the right ideas, and if I’ve missed any important bits.

Temporal coverage (preliminary)

---

stash-merritt/lib/stash/merritt/object_manifest_package.rb
stash_api/app/controllers/stash_api/application_controller.rb
stash_api/app/controllers/stash_api/files_controller.rb
stash_api/app/controllers/stash_api/urls_controller.rb
stash_api/app/models/stash_api/file.rb
stash_api/spec/factories/stash_engine/file_uploads.rb
stash_api/spec/unit/models/stash_api/file_spec.rb
stash_engine/app/models/stash_engine/file_upload.rb
stash_engine/db/migrate/20181009225639_add_digest_to_file_uploads.rb
stash_engine/spec/db/stash_engine/file_upload_spec.rb

I've added some testing instructions in the comments in the ticket at https://github.com/CDL-Dryad/dryad-product-roadmap/issues/91 about how this all works.
I have a task to update all the documentation for later in the sprint.

Allow adding file digests, digestType and description to a file

---

stash_api/app/controllers/stash_api/datasets_controller.rb
stash_datacite/app/models/stash_datacite/description.rb
stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/controllers/stash_engine/curation_activity_controller.rb
stash_engine/app/controllers/stash_engine/shared_security_controller.rb
stash_engine/app/models/stash_engine/author.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/views/stash_engine/admin_datasets/_activity_log_row.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_curation_note_popup.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_curation_state_popup.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_filter.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_search.html.erb
stash_engine/app/views/stash_engine/admin_datasets/activity_log.html.erb
stash_engine/app/views/stash_engine/admin_datasets/index.html.erb
stash_engine/app/views/stash_engine/admin_datasets/note_popup.js.erb
stash_engine/app/views/stash_engine/admin_datasets/status_popup.js.erb
stash_engine/app/views/stash_engine/curation_activity/status_change.js.erb
stash_engine/config/routes.rb
stash_engine/db/migrate/20181116000227_add_search_words_to_identifier.rb
stash_engine/lib/tasks/stash_engine_tasks.rake
stash_engine/spec/db/stash_engine/identifier_spec.rb

This includes the changes for the other things in the admin area because it is dependent (see previous pull requests).
Implements UI as shown at http://ux.cdlib.org/jlee/completed/dryad_03oct2018/#g=1&p=dataset_activity_log .  You can get to the page in the admin area by clicking the clock icon next to the "last modified" such as at http://ux.cdlib.org/jlee/completed/dryad_03oct2018/#g=1&p=admin_dashboard_v2 .

Displays the activity log for the admin area

---

stash_api/app/controllers/stash_api/datasets_controller.rb
stash_datacite/app/models/stash_datacite/description.rb
stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/models/stash_engine/author.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_search.html.erb
stash_engine/db/migrate/20181116000227_add_search_words_to_identifier.rb
stash_engine/lib/tasks/stash_engine_tasks.rake
stash_engine/spec/db/stash_engine/identifier_spec.rb

The search interface is kind of dumb because we have relevance ranking of some kind but the more words you add, the more random things it brings up and the rest of the interface has different sorts that will fight with each other.
I think this design is poorly thought out, but whatever.  It return some things that are getting a score of 50% or above and leaving off the really irrelevant stuff.  You can see some of the fun as you add multiple words and phrases.
We can revisit later if it's not working well enough or get a redesign from Jane that makes more sense.
Test it out and see what fun happens.

Should be able to search in the admin area in a kind of meaningful way

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/controllers/stash_engine/internal_data_controller.rb
stash_engine/app/views/stash_engine/admin_datasets/_internal_data_popup.html.erb
stash_engine/app/views/stash_engine/admin_datasets/activity_log.html.erb
stash_engine/app/views/stash_engine/admin_datasets/data_popup.js.erb
stash_engine/app/views/stash_engine/curation_activity/status_change.js.erb
stash_engine/app/views/stash_engine/internal_data/_table.html.erb
stash_engine/app/views/stash_engine/internal_data/create.js.erb
stash_engine/app/views/stash_engine/internal_data/destroy.js.erb
stash_engine/app/views/stash_engine/internal_data/update.js.erb
stash_engine/config/routes.rb

It's quite basic, I will add ISSN lookup based on Daisie's code soon.
Click the admin area.  Click the little clock icon for a dataset.  Look at the bottom of the page to work with the internal data.  https://github.com/CDL-Dryad/dryad-product-roadmap/issues/153

This allows curators to enter/edit/delete internal data

---

.gitignore

Not sure why I had this directory at this location, but I'm just going to ignore it.  Maybe I ran something in the wrong location.

adding node_modules to ignore

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/sessions/choose_login.html.erb

Fixes to issues with Author and Last Modified By sorts on the admin page.
Also snuck in a minor text revision to the login page in this one :)

fixed issues with admin page sorts

---

stash_api/app/controllers/stash_api/curation_activity_controller.rb

Some minor changes to the API for curation_activity to bring it in line with the new code in the model.

Curation api update

---

stash_engine/app/views/stash_engine/pages/_nav.html.erb
stash_engine/app/views/stash_engine/pages/about.html.erb
stash_engine/app/views/stash_engine/pages/help.html.erb

Fixed issue with the about/help links and removed duplicate h1

Fix about help links

---

stash_engine/app/views/stash_engine/shared/_footer.html.erb

Updated copyright statement to only list Dryad

Removed UC regents from copyright

---

stash_engine/app/views/stash_engine/pages/_nav.html.erb
stash_engine/app/views/stash_engine/pages/about.html.erb

- Updated route helpers to pass in anchors
- commented out TOC on about

fixed issue with about-help links

---

stash_engine/app/controllers/stash_engine/landing_controller.rb

This is a super small change, but make it so invitation emails get sent without error.

This is a dumb fix which will be sure that the resource method operates right

---

stash_engine/app/views/stash_engine/pages/_nav.html.erb

Fixes an issue where the nav links were broken when viewing pages generated by the stash_discovery engine

added stash_url_helpers to nav links

---

stash_datacite/app/views/stash_datacite/resources/_submitted_line.html.erb

For https://github.com/CDL-Dryad/dryad-product-roadmap/issues/226

Prevent user from Updating dataset when its in curation

---

stash_engine/app/controllers/stash_engine/shared_controller.rb

per https://github.com/CDL-Dryad/dryad-product-roadmap/issues/244

Fix dates on My Datasets page

---

stash_datacite/app/views/stash_datacite/licenses/_review.html.erb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/spec/db/stash_engine/identifier_spec.rb

When a journal or institution pays, show the respective name. https://github.com/CDL-Dryad/dryad-product-roadmap/issues/231
Also refactor to improve capabilities retrieval of journal metadata and its tests.

Improve messages for journal-pay and institution-pay scenarios

---

stash_engine/app/models/stash_engine/identifier.rb

I already made a tag based on our previous tag, but with the error fixed and deployed to dev and stage.  But I'm going to do a PR so that what I have also gets fixed in master (and Ryan can come back and fix some more with this bug report at https://github.com/CDL-Dryad/dryad-product-roadmap/issues/264 ).
I'm mostly just checking http status codes for the response, checking for blank? in some places and rescuing some network errors in case they come up.

Fix submitter country to avoid errors

---

stash_engine/app/views/stash_engine/user_mailer/published.html.erb
stash_engine/spec/unit/mailers/user_mailer_spec.rb

Per conversation with @dlowenberg we are just going to reference the DOI in the published email.

updated published email citation

---

stash_engine/app/models/stash_engine/resource.rb

Update to nil checks on Resource.dataset_in_progress_editor_id

updated nil check on resource dataset_in_progress_editor_id

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/models/stash_engine/resource.rb

Addresses bug on the Admin page for sorting or filtering by curation status

Status filter bugfix

---

stash_engine/app/controllers/stash_engine/widgets_controller.rb
stash_engine/lib/stash/organization/ror.rb

This also goes with a pull request in the Dryad repo for the tests of the controller request.

Get the IDs both from the internal data table instead of the main DOI

---

stash_api/app/models/stash_api/dataset_parser.rb
stash_datacite/app/controllers/stash_datacite/affiliations_controller.rb
stash_datacite/app/views/stash_datacite/authors/_affiliation.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_filter.html.erb
stash_engine/lib/stash/organization/ror.rb

Related to bugs found in dryad repo tests

changes to accomodate fixes to issues found in dryad repo tests

---

stash_engine/app/controllers/stash_engine/landing_controller.rb
stash_engine/app/views/stash_engine/landing/_metrics.html.erb
stash_engine/app/views/stash_engine/landing/_sidebar.html.erb
stash_engine/app/views/stash_engine/landing/metrics.js.erb
stash_engine/config/routes.rb

I'm just merging the upstream changes we had to make for COUNTER stats and whatever else to keep the pages loading.
There is another ticket about this https://github.com/CDL-Dryad/dryad-product-roadmap/issues/273 which we'll do more work on.

Merge upstream

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb

for ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/307
Natural language searches not allowing partial text (e.g. 'mcsweeney' finds records associated with 'Gloriana McSweeney' but 'mcswee' returns nothing)
Tried following the MySQL docs and switched using the wildcard for the MATCH AGAINST query type (e.g. `MATCH(stash_engine_identifiers.search_words) AGAINST(?*) > 05`) but it doesn't seem to make any difference.
So, I added logic to do a `LIKE '%[keyword]%' if the normal natural language search returns nothing (only fires if the search term has at least 4 characters)
This solution has 2 negatives:
- it does not commingle the 2 search types, so a search for 'optic' returns only the natural language hits for the word 'optic' (assuming there are matches) and would not …

Fix for Admin search

---

.gitignore
stash_engine/app/assets/stylesheets/stash_engine/ui.css
stash_engine/public/demo/css/ui.css
stash_engine/ui-library/scss/_progress.scss

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/266

fixed issue with dataset nav arrows

---

stash_discovery/app/controllers/catalog_controller.rb

For ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/344

removed year facet from the solr search results

---

stash_engine/app/models/stash_engine/internal_datum.rb

For https://github.com/CDL-Dryad/dryad-product-roadmap/issues/334
Add field types to the internal datum, allowing references to the dark archive at DANS.

Add DANS fields to internal data

---

stash_engine/app/assets/stylesheets/stash_engine/ui.css
stash_engine/public/demo/css/ui.css
stash_engine/ui-library/scss/_data-list.scss
stash_engine/ui-library/scss/_dependency-list.scss
stash_engine/ui-library/scss/_headings.scss
stash_engine/ui-library/scss/_login.scss
stash_engine/ui-library/scss/_variables.scss

The gulp build process was running a Sass linter task that had errors preventing the CSS assets from compiling. Cleaned up the issues and reran `gulp build`

Fixed Sass linter issues

---

stash_engine/app/views/stash_engine/landing/_files_embargoed.html.erb

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/355

updated embargoed text on landing page

---

stash_engine/app/assets/stylesheets/stash_engine/ui.css
stash_engine/app/views/stash_engine/pages/_nav.html.erb
stash_engine/app/views/stash_engine/pages/_why_share.html.erb
stash_engine/app/views/stash_engine/pages/_why_use.html.erb
stash_engine/app/views/stash_engine/pages/about.html.erb
stash_engine/app/views/stash_engine/pages/terms.html.erb
stash_engine/app/views/stash_engine/shared/_footer.html.erb
stash_engine/config/routes.rb
stash_engine/public/demo/css/ui.css
stash_engine/ui-library/scss/_about.scss
stash_engine/ui-library/scss/main.scss

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/259
- Added new terms of service page to footer
- Text changes to items in the main nav menu
- Minor text change on 'Why use' page
- Updated links in the 'How it Works' section of homepage
- New sass for governance/staff pics

Public facing page changes

---

stash_datacite/app/controllers/stash_datacite/authors_controller.rb

Not sure of the best way to duplicate the original issue reported in https://github.com/CDL-Dryad/dryad-product-roadmap/issues/311
Added some nil checks to the 2 helper methods on the controller that should prevent the error going forward.

added nil checks to authors_controller

---

stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/lib/stash/doi/datacite_gen.rb
stash_engine/lib/stash/doi/ezid_gen.rb
stash_engine/lib/stash/doi/id_gen.rb
stash_engine/spec/unit/models/curation_activity_spec.rb
stash_engine/spec/unit/stash/doi/datacite_gen_spec.rb
stash_engine/spec/unit/stash/doi/ezid_gen_spec.rb

@sfisher this PR contains some better error handling that should give us more insight into Datacite errors.
added tests for it as well

added better error handling to Ezid and Datacite services

---

stash_datacite/app/views/stash_datacite/shared/_citations_pdf.html.erb

fixed name of publication_year variable for ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/356
will add a test to the dryad repo that ensures the page loads in the future :)
You can test with this dataset: 10.5061/dryad.v2j62h1

updated data paper citation section

---

stash_engine/lib/stash/organization/ror.rb

Updated ROR API call based on conversation with their team:
https://github.com/CDL-Dryad/dryad-product-roadmap/issues/386

updated ROR api query param

---

stash-merritt/lib/stash/merritt/object_manifest_package.rb
stash-merritt/lib/stash/merritt/submission_job.rb
stash-merritt/lib/stash/merritt/zip_package.rb
stash-merritt/spec/db/stash/merritt/zip_package_spec.rb
stash-merritt/spec/unit/stash/merritt/submission_job_spec.rb

After we had errors in Dash with cleanup, i wanted to sure it was all gone.
I believe I already removed (most of it), but I went through and found references an removed all the stuff we don't use.
I also looked at when we use cleanup and the methods are still there.  This was mostly spelunking through lots of nested inheritance and finding methods that call other methods to be sure I got stuff.

Cleanup any extra files cleanup code to simplify

---

stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/views/stash_engine/admin_datasets/_curation_activity_form.html.erb
stash_engine/lib/stash/doi/ezid_gen.rb
stash_engine/spec/unit/models/curation_activity_spec.rb
stash_engine/spec/unit/stash/doi/ezid_gen_spec.rb

Continuation of ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/376

UI update to show error message to curators/admins on Datacite/Ezid failures

---

stash-notifier/app/collection_set.rb
stash-sword/lib/stash/sword/client.rb
stash_api/app/controllers/stash_api/curation_activity_controller.rb
stash_datacite/app/controllers/stash_datacite/peer_review_controller.rb
stash_datacite/app/models/stash_datacite/publication_year.rb
stash_engine/app/controllers/stash_engine/admin_controller.rb
stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/controllers/stash_engine/admin_datasets_controller/stats.rb
stash_engine/app/controllers/stash_engine/downloads_controller.rb
stash_engine/app/controllers/stash_engine/sessions_controller.rb
stash_engine/app/controllers/stash_engine/shared_controller.rb
stash_engine/app/controllers/stash_engine/submission_queue_controller.rb
stash_engine/app/models/stash_engine/counter_stat.rb
stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/models/stash_engine/file_upload.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/models/stash_engine/user.rb
stash_engine/app/views/stash_engine/landing/_files_embargoed.html.erb
stash_engine/app/views/stash_engine/status_dashboard/show.html.erb
stash_engine/app/views/stash_engine/submission_queue/_status_table.html.erb
stash_engine/lib/stash/datacite_metadata.rb
stash_engine/lib/stash/doi/id_gen.rb
stash_engine/lib/stash/download/base.rb
stash_engine/lib/stash/event_data/citations.rb
stash_engine/lib/stash/event_data/usage.rb
stash_engine/lib/stash_engine/counter_log.rb
stash_engine/lib/tasks/link_out.rake
stash_engine/lib/tasks/stash_engine_tasks.rake

Updated codebase to use UTC.
For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/360

Updated all Time.new and Time.now to Time.new.utc and Time.now.utc

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/391
Updated Kaminari to use array instead of its default ActiveRecord results

fixed issue with kaminari paging

---

stash_engine/app/assets/stylesheets/stash_engine/ui.css
stash_engine/app/views/stash_engine/pages/our_platform.html.erb
stash_engine/public/demo/css/ui.css
stash_engine/ui-library/scss/_about.scss

SCSS fix for table on our platform page

fixed issue with display of table on our_platform page

---

stash_engine/app/services/stash_engine/status_dashboard/dependency_checker_service.rb

copy paste error after moving log file logic to abstract class

fixed bug in external dependency checker

---

stash_engine/lib/tasks/counter.rake

These are for tasks 389 and 228.
See also changes in the config repo.
The changes pull in the settings from environment variables instead of fixed constants.  Also added a test rake task to be sure they are pulled in correctly.

Adding the script and cron to the config

---

stash_engine/app/views/stash_engine/file_uploads/_redraw_files_table.js.erb
stash_engine/app/views/stash_engine/file_uploads/destroy_error.js.erb
stash_engine/app/views/stash_engine/resources/upload.html.erb
stash_engine/app/views/stash_engine/resources/upload_manifest.html.erb

It was trying to javascript_escape a symbol instead of a string which caused errors in rails, so converting symbol to string.

Not search words, but fixing problems I found in the js_escape stuff

---

script/mdc-to-log/README.md
stash_engine/lib/tasks/counter/validate_file.rb

Just changes to output info about problems in counter files and also work around some of the problems.

More info bad counter

---

stash_engine/lib/stash/link_out/helper.rb
stash_engine/lib/stash/link_out/labslink_service.rb
stash_engine/lib/stash/link_out/pubmed_sequence_service.rb
stash_engine/lib/stash/link_out/pubmed_service.rb
stash_engine/lib/tasks/link_out.rake

Updated the urls that are embedded in the LinkOut files to use https per email conversation with Lidia at PubMed.
Enabled FTP functionality for each service.

Enabled FTP portion of LinkOut Services and updated URLs

---

stash_datacite/app/views/stash_datacite/descriptions/_show.html.erb
stash_datacite/app/views/stash_datacite/resources/_review.html.erb
stash_datacite/app/views/stash_datacite/resources/_show.html.erb
stash_datacite/app/views/stash_datacite/resources/_show_pdf.html.erb
stash_engine/app/assets/stylesheets/stash_engine/ui.css
stash_engine/app/models/stash_engine/file_upload.rb
stash_engine/app/views/stash_engine/landing/_metrics.html.erb
stash_engine/public/demo/css/ui.css
stash_engine/ui-library/scss/_landing.scss

These are just tweaks to the layout and hiding maps and making text look better mostly.
Also replacing released directory with "current" in file paths if it contains it so we don't have problems with file uploads.

Release ann tweaks

---

stash_engine/app/models/stash_engine/counter_stat.rb
stash_engine/lib/tasks/counter.rake
stash_engine/lib/tasks/counter/json_stats.rb

This is a task to manually populate our stats into our database even though DataCite chokes on them because of our data being inconsistent.

This is for processing stats manually from our own files.

---

README.md

Add deprecation info to the repo and direct people to use our combined repo

Deprecating this repository and info
