CDL-Dryad/stash

stash_discovery/stash_discovery.gemspec

Deals with an [issue](https://github.com/ffi/ffi/issues/640) where native extensions of recent versions of the [ffi](https://github.com/ffi/ffi) gem (a transitive dependency of Geoblacklight) won't build on macOS by explicitly requiring the gem and pegging it at a specific version that's known to build.
We should be able to remove this line from the Gemspec once ffi's issue is fixed.

Peg ffi to version 1.9.21 for https://github.com/ffi/ffi/issues/640

---

stash_engine/app/views/stash_engine/shared/_footer.html.erb

This is a change to get application functioning after the deploy and using the new login link which we missed and didn't see until we deployed on real server.  The homepage should load without error with this change.

small change to get tenant working on server with login in footer

---

stash_engine/app/controllers/stash_engine/dashboard_controller.rb
stash_engine/app/mailers/stash_engine/migration_mailer.rb
stash_engine/app/models/stash_engine/user.rb
stash_engine/app/views/stash_engine/dashboard/migrate_data.html.erb
stash_engine/app/views/stash_engine/dashboard/migrate_data_mail.html.erb
stash_engine/app/views/stash_engine/dashboard/migrate_successful.html.erb
stash_engine/app/views/stash_engine/dashboard/show.html.erb
stash_engine/app/views/stash_engine/migration_mailer/migration_email.text.erb
stash_engine/config/routes.rb
stash_engine/db/migrate/20180718223728_add_migration_token.rb
stash_engine/test/mailers/previews/stash_engine/migration_preview.rb
stash_engine/test/mailers/stash_engine/migration_test.rb

Creates the ability to connect (in theory) old Dryad accounts, keyed on email addresses, to new Dryad accounts.
If someone enters this workflow from their dashboard, they will be offered the ability to enter an email associated with an old Dryad account. Currently, this is not verified to be attached to an old Dryad account in any way: it merely generates a token that is sent to that email address, so that we can verify that this user can access that email address.
To test: from the user dashboard, click on the “Migrate my data” button. You should be able to enter in an email address, obtain the token, and enter that token in on the following page. If you enter it incorrectly, you’ll go back to the first page in the path. This probably will need to be tweaked for real deployment, with …

Migrate mailer

---

stash_engine/app/controllers/stash_engine/sessions_controller.rb
stash_engine/app/controllers/stash_engine/shared_security_controller.rb
stash_engine/app/models/stash_engine/tenant.rb
stash_engine/app/views/stash_engine/sessions/choose_sso.html.erb
stash_engine/spec/unit/models/tenant_spec.rb

This allows shibboleth login and is currently deployed on dryad-dev.cdlib.org.
Testing:
- delete your user record from the database
- log in
- select ucop
- log in by shib
- land on your datasets page
- check database for your user record.  You should see it is set to ucop if you logged in by shibboleth ucop.

Shibboleth set tenant

---

stash_engine/app/controllers/stash_engine/sessions_controller.rb
stash_engine/app/models/stash_engine/user.rb

https://github.com/CDL-Dryad/dryad-product-roadmap/issues/30
Adding the email if unverified and we can get it.  I also made some changes to the user model and use of email as a local variable since email is also an activerecord field so may cause problems or confusion.
I tested this with a new orcid sandbox account after setting the email to partner (and unverified) and it worked for me.

Even unverified emails will get populated in DB table if Dryad exposes them for a user after they log in

---

stash_engine/config/initializers/omniauth.rb

Add ryandash.datadryad.org to the list of servers that do not get https
when receiving a redirect from ORCID. This allows Ryan's vagrant server to work 
properly with the ORCID sandbox.

Update list of exceptions for https

---

stash_engine/config/initializers/omniauth.rb

This gives us one fix that allows any dev to add a VM if they use a hostname in this style.

Include all *dash.datadryad.org servers in the exclusion

---

stash_api/app/controllers/stash_api/application_controller.rb
stash_api/app/controllers/stash_api/datasets_controller.rb
stash_api/app/models/stash_api/dataset.rb
stash_api/spec/unit/models/stash_api/dataset_spec.rb

Datasets should be able to be referenced both by their DOI-type identifier (`identifier`) and their internal numeric id (`id`). Both should be discoverable via a GET request.

Dataset identifiers

---

stash_engine/db/migrate/20181008011048_add_embargo_type_to_stash_engine_embargoes.rb

Add a field to the resources table for storing the type of an embargo. This will be needed for historical data, even if embargo types are not used in the future.

Add embargo type

---

stash_api/app/controllers/stash_api/curation_activity_controller.rb
stash_api/app/models/stash_api/dataset.rb
stash_engine/app/controllers/stash_engine/curation_activity_controller.rb
stash_engine/app/models/stash_engine/curation_activity.rb

A dataset’s status is equal to the status of the last status-changing curation_activity that is recorded for it. If there is no curation_activity, its status is “Unsubmitted”.

Add ability to get the current status of a Dataset

---

stash_datacite/app/models/stash_datacite/resource/completions.rb

A refinement of #40, allowing items submitted through the API to go through without an abstract. There are a few items in Dryad Classic that do not have abstracts, and it seems better to allow them rather than putting in a dummy abstract.

When using loosenValidation, do not require an abstract

---

stash-merritt/lib/stash/merritt/submission_job.rb

This is the functional part of #43, without the extra commit that we didn't want.

skip reserving id for identifiers with skipDataciteUpdate flag

---

stash_engine/app/controllers/stash_engine/resources_controller.rb
stash_engine/lib/tasks/identifier_rake_functions.rb
stash_engine/lib/tasks/stash_engine_tasks.rake

This task is based on this issue.  https://github.com/CDL-Dryad/dryad-product-roadmap/issues/109
The easiest way to test will be to log in to the UI and create a new dataset and you could then trace it in the database to see that a stash_engine_identifier has been created for the stash_engine_resource.
I have also tested out submissions made this way in the UI and it worked correctly and doesn't re-mint or change the identifier.
----
I also added a rake task you can run from the main application with `RAILS_ENV=<your-env-here> rake fix_missing_stash_engine_identifiers`
If you run it, it will find and update any missing identifiers.  It's a good thing to do so things are consistent for old resources that might not have them when we transition from old code to new.
If you want to test on …

Mint id early to avoid problems with non-existent stash_engine_identifier objects

---

stash_engine/app/models/stash_engine/resource.rb

… Adding these make it so a "destroy" on resource will also destroy these and not leave orphan records hanging in the database.  Needed for clearing script.

I am simply adding associations that were missing from ActiveRecord

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_filter.html.erb

You can test by logging in as a superuser and then clicking the admin link.
We don't have a lot of data (it was easier to test before with more variety).
Should be able to sort, filter and page through things.
There is no user information for the unsubmitted status, it seems like.
We were waiting on publication date for a conversation about what it meant, exactly, with publishing and versioning and if it would really always be the last status.
This depends on the previous admin features.

Paging, sorting and filtering on the Admin page

---

stash_api/app/controllers/stash_api/datasets_controller.rb
stash_datacite/app/models/stash_datacite/description.rb
stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/controllers/stash_engine/curation_activity_controller.rb
stash_engine/app/controllers/stash_engine/shared_security_controller.rb
stash_engine/app/models/stash_engine/author.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/views/stash_engine/admin_datasets/_curation_state_popup.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_filter.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_search.html.erb
stash_engine/app/views/stash_engine/admin_datasets/index.html.erb
stash_engine/app/views/stash_engine/admin_datasets/status_popup.js.erb
stash_engine/app/views/stash_engine/curation_activity/status_change.js.erb
stash_engine/config/routes.rb
stash_engine/db/migrate/20181116000227_add_search_words_to_identifier.rb
stash_engine/lib/tasks/stash_engine_tasks.rake
stash_engine/spec/db/stash_engine/identifier_spec.rb

This PR incorporates code from the previous PR since they build on each other. 
This enables a javascript modal dialog for changing the status from the admin chart like shown at http://ux.cdlib.org/jlee/completed/dryad_03oct2018/#g=1&p=admin_dashboard_v2 .  (click the pencil under status in the wireframe.)
It sounds like we'll have a meeting about status workflow early next week ahead of our next sprint to iron out more details of how it would work in other areas.

Setting curation status for a dataset

---

stash_api/app/controllers/stash_api/curation_activity_controller.rb
stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/models/stash_engine/identifier_state.rb
stash_engine/db/migrate/20181203191849_change_curation_activity_note_to_text.rb

When migrating older provenance messages, make sure they don’t unnecessarily change the current curation state.
In addition, if there isn’t a user specified for a curation activity, return “System”.

Tweaks for migrating provenances

---

stash_datacite/app/controllers/stash_datacite/resources_controller.rb
stash_datacite/app/views/stash_datacite/resources/_review.html.erb
stash_engine/app/views/stash_engine/shared/_dataset_steps_bottom_nav.html.erb
stash_engine/app/views/stash_engine/shared/_dataset_steps_nav.html.erb
stash_engine/spec/unit/models/tenant_spec.rb

This allows curators to view and edit the files attached to a dataset.  These are mostly simple UI changes to change navigation options.
https://github.com/CDL-Dryad/dryad-product-roadmap/issues/115
I added code so things are not updated to DataCite because it all fails with multiple versions after they delete them and they are soon getting ride of test identifiers, anyway.
The updates to DataCite will be moved to the embargo setting or publication step in curation status, anyway, and not tied to submission, so this will all be changed or gutted soon.

Enable file upload

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/views/stash_engine/admin_datasets/index.html.erb
stash_engine/app/views/stash_engine/admin_datasets/index.tsv.erb

If you go into the Admin area and click the link at the bottom that says "Get Tab Separated Values (TSV) for import into Excel" it will export this and you can open in Excel or similar program.  It exports without paging in one big TSV file.
I assume people will filter down, such as for items that are in a particular state that they need to look at and then export.
https://github.com/CDL-Dryad/dryad-product-roadmap/issues/151
This is deployed on dryad-dev.cdlib.org

Allowing Tab Separated Value download for Excel

---

stash-wrapper/CHANGES.md
stash-wrapper/LICENSE.md
stash_engine/app/assets/javascripts/stash_engine/metadata_entry_pages.js
stash_engine/app/assets/javascripts/stash_engine/ui.js
stash_engine/app/models/stash_engine/user.rb
stash_engine/app/views/layouts/stash_engine/application.html.erb
stash_engine/app/views/stash_engine/dashboard/ajax_wait.js.erb
stash_engine/app/views/stash_engine/shared/_dataset_steps_bottom_nav.html.erb
stash_engine/app/views/stash_engine/shared/_dataset_steps_nav.html.erb
stash_engine/app/views/stash_engine/shared/_footer.html.erb
stash_engine/app/views/stash_engine/shared/_log_in_out.html.erb

These are mostly changes made to make saving of the Abstract more reliable in the UI, especially when using Apple Safari where it had problems more often.  To test, fill in an abstract and then click the "next page" button at the bottom without clicking outside the abstract first.
The Javascript changes explicitly add css classes for javascript attachment to links that will navigate off page.  The attached script then delays, allowing AJAX to start and then checks jQuery AJAX request counts on a timer until count goes to 0 before going to the new URL.
It looks like some release notes were changed by David M sometime in Dash, also.

Merging in changes made to Dash into Dryad

---

stash_datacite/app/controllers/stash_datacite/landing_mixin.rb

In the publisher in citations it would put "Dash" after the publisher name, so something like "Dryad Dash."
Removing this from the citation.
This is a very small task.

Remove dash publisher

---

stash_datacite/app/controllers/stash_datacite/resources_controller/dataset_presenter.rb

The display of bad dataset curation statuses results in blanks in the my datasets page now.

Making it not barf without curation statuses to display

---

stash_engine/app/controllers/stash_engine/dashboard_controller.rb
stash_engine/app/views/stash_engine/sessions/choose_login.html.erb
stash_engine/app/views/stash_engine/sessions/choose_sso.html.erb

Also trying to fix the asset pipeline problem with orcid icon randomly not displaying on stage.  People online say that adding the file extension may fix this weird problem.
To test the affiliation not being set.
1.  Delete affiliation in DB.
2. Log in.
3. When asked for affiliation, click "My Datasets" and pretend you were never asked to do anything.
4. You should get redirected back to this page with a message telling you to fill in your f-ing affiliation.
I don't know if adding the svg to the image_tag filename will fix this problem.  It works fine on development and I don't think we'll know until we deploy to stage.  Some people online think it randomly fixes this weird problem.

Making people put in their affiliation before they can start a dataset

---

stash_api/Gemfile.lock
stash_api/app/controllers/stash_api/files_controller.rb
stash_datacite/Gemfile.lock
stash_engine/Gemfile
stash_engine/Gemfile.lock
stash_engine/app/controllers/stash_engine/file_uploads_controller.rb
stash_engine/app/models/stash_engine/file_upload.rb
stash_engine/app/models/stash_engine/url_validator.rb
stash_engine/db/migrate/20190228182559_add_original_file_name_to_stash_engine_file_uploads.rb
stash_engine/spec/db/stash_engine/file_upload_spec.rb
stash_engine/stash_engine.gemspec

- Added the Zaru gem to the Gemfile
- Added a `sanitize_file_name(name)` class method to the FileUpload model
- Updated FileUpload controller to sanitize incoming file uploads and Url based files
- Added `stash_engine_file_uploads.original_filename` so that we have the original unsanitized name should we want to somehow notify the user in the UI that the name changed.

Filename sanitization

---

stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/views/stash_engine/admin_datasets/curation_activity_popup.js.erb
stash_engine/spec/db/stash_engine/curation_activity_spec.rb

Some additional tweaks to the embargo cleanup
- fixed typo in definition of callback conditional
- @ryscher confirmed that `submit_to_stripe` should only be called if the dataset is published or embargoed (logic is still in place to make sure we have not already invoiced for the dataset)
- updated all callback tests to check 'embargoed' state
- removed `console.log` statement from JS

Updated `submit_to_stripe` callback so that it happens on published/embargoed

---

stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/views/layouts/stash_engine/application.html.erb

- reloads self after Resource model initializes dependencies (to ensure refs to latest/current are up to date)
- make sure initial curation_activity uses the user_id on the resource
- add check for missing current_tenant on application.html.erb

Minor changes discovered when building out new test framework on Dryad repo

---

stash_api/.rubocop.yml
stash_api/app/controllers/stash_api/curation_activity_controller.rb
stash_api/app/controllers/stash_api/datasets/submission_mixin.rb
stash_api/app/controllers/stash_api/datasets_controller.rb
stash_api/app/controllers/stash_api/files_controller.rb
stash_api/app/controllers/stash_api/urls_controller.rb
stash_api/app/models/stash_api/dataset_parser.rb
stash_api/app/models/stash_api/dataset_parser/related_works.rb
stash_api/app/models/stash_api/user.rb
stash_api/app/models/stash_api/version/metadata.rb
stash_api/lib/core_extensions/hash/recursive_compact.rb
stash_api/spec/unit/models/stash_api/dataset_spec.rb
stash_datacite/app/controllers/stash_datacite/resources_controller.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/models/stash_engine/resource_state.rb
stash_engine/db/migrate/20190322184657_add_preserve_curation_status_to_resource.rb

Allows API users to set a flag `preserveCurationStatus` on a resource. When this flag is active, changes to the Merritt resource_state will not affect the resource's curation status. https://github.com/CDL-Dryad/dryad-product-roadmap/issues/225
Also fixes a bug that was preventing the API from setting any curation status information.
Note there is a database migration required for this PR.
To test: submit a resource using the API, where `preserveCurationStatus` is true. Submit some curation status through the API that is not `submitted`. After being processed through Merritt, the resource should still have the appropriate curation status.

Preserve curation status

---

stash-merritt/spec/db/stash/merritt/repository_spec.rb
stash_api/spec/unit/models/stash_api/dataset_parser_spec.rb
stash_datacite/spec/db/stash_engine/resource_spec.rb
stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/controllers/stash_engine/curation_activity_controller.rb
stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/models/stash_engine/resource_state.rb
stash_engine/app/views/stash_engine/admin_datasets/_curation_activity_form.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_edit_dataset_button.html.erb
stash_engine/config/routes.rb
stash_engine/lib/stash/repo/repository.rb
stash_engine/spec/db/stash_engine/curation_activity_spec.rb
stash_engine/spec/db/stash_engine/resource_spec.rb
stash_engine/spec/db/stash_engine/resource_state_spec.rb
stash_engine/spec/db/stash_engine/user_spec.rb

Reconfigured relationship between Resource and CurationActivity. Removed callbacks that were managing curation status.
Updated one of the stash_engine routes which was throwing a deprecation warning.
Added a bunch of tests to Dryad repo to verify that these changes are working and that resource versioning functions properly.

Status workflow

---

travis-build.rb

The warn method was calling itself and giving us colorize errors anytime there were errors in a test.

Infinite recursion isn't good

---

stash_engine/app/models/stash_engine/curation_activity.rb

Callback on CurationActivity is already triggered so removing the call within the submit_datacite method

Fix for bug causing 2 emails to be sent to author when publishing a dataset

---

stash_datacite/spec/db/stash_datacite/author_spec.rb
stash_engine/app/models/stash_engine/author.rb
stash_engine/db/migrate/20190410162918_move_customer_id_from_stash_engine_users_to_stash_engine_authors.rb
stash_engine/lib/stash/payments/invoicer.rb
stash_engine/spec/db/stash_engine/author_spec.rb
stash_engine/spec/unit/stash/payments/invoicer_spec.rb

- added migration to remove `stash_engine_users.customer_id` and add `stash_engine_authors.stripe_customer_id`
- added `StashEngine::Author.primary(resource_id)` scope that returns the first Author that has an email (UI already verifies that there is at least one with email)
- refactored `Stash::Payments::Invoicer` to work with authors instead of user
- refactored `Stash::Payments::Invoicer` to encapsulate Stripe calls (was really just an easy way to double/mock Stripe)
- Added tests for `Stash::Payments::Invoicer` to test scenarios: A) No authors for some reason, B) Author that has never had a Stripe invoice from us, C) Author who has already had a Stripe invoice from us

Update Stripe to use author email 

---

stash_api/app/controllers/stash_api/datasets_controller.rb
stash_api/app/models/stash_api/dataset_parser.rb
stash_api/spec/unit/models/stash_api/dataset_parser_spec.rb

When creating a new dataset, allow API superusers to specify an `invoiceId`, which will be stored in the identifier.invoice_id field.
This  is needed to migrate content from the old Dryad system, most of which has already been invoiced/paid.

Add invoiceId to the API for creating new datasets

---

stash_api/app/controllers/stash_api/curation_activity_controller.rb

Somehow these two lines were using a non-existent `date` variable. Replacing it with a valid date.

Bugfix: set date when API call doesn't have created_at

---

stash_engine/app/controllers/stash_engine/landing_controller.rb

As a superuser, try to view the landing page for an item that is in another user's workspace. You will receive a null pointer error or InvalidComponentError unless this fix is in place.

Remove errors when viewing an item in a user workspace

---

stash_engine/app/views/stash_engine/sessions/choose_sso.html.erb

There aren't a lot of partners so just reverted back to a select box to deal with issue where the list displays names but when an item is selected it displays the abbreviation in the textbook.

Reverted SSO selection from datalist back to a select box

---

stash_datacite/app/controllers/stash_datacite/landing_mixin.rb
stash_datacite/app/helpers/stash_datacite/resources_helper.rb
stash_datacite/app/views/stash_datacite/resources/_review.html.erb
stash_datacite/app/views/stash_datacite/resources/_show.html.erb
stash_datacite/app/views/stash_datacite/resources/_show_pdf.html.erb
stash_datacite/app/views/stash_datacite/shared/_citations.html.erb
stash_engine/app/views/stash_engine/landing/_files.html.erb

Code was using `resource.updated_at` so updated to instead use `resource.publication_date`. The code defaults to the old `updated_at` if there is no `publication_date` defined to allow the page to continue to display in the event that there's an issue

Updates to landing page to use publication_date instead of updated_at

---

stash_datacite/lib/stash/indexer/indexing_resource.rb
stash_datacite/spec/factories.rb
stash_datacite/spec/unit/stash/indexer/indexing_resource_spec.rb
stash_discovery/app/controllers/catalog_controller.rb
stash_discovery/app/controllers/latest_controller.rb
stash_discovery/app/views/catalog/_home_text.html.erb
stash_discovery/lib/tasks/rsolr.rake

- Added `dryad_related_publication_name_s` to stash_datacite and stash_discovery.
- Added new `rsolr:reindex` rake task to resubmit datasets with the journal name.
@sfisher I updated the `schema.xml` and `solrconfig.xml` on the solr server in the `apps/solr/data/geoblacklight/conf` directory. I'm not sure where these files are managed
goes with the corresponding updates to dryad_config repo

added journal facet to solr

---

stash_engine/config/initializers/licenses.rb

See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/287 for an explanation of this problem.
This merges across **all 3 repos.**  I've added a test for the method that loads the dynamically inserted test environment information into yml files.  I couldn't get database.yml to substitute, but I think I got most of the rest and I'm not sure the database.yml is so much of a problem.

Make both travis and local tests use dryad-config-example settings

---

stash_datacite/app/models/stash_datacite/affiliation.rb
stash_datacite/app/views/stash_datacite/licenses/_review.html.erb
stash_datacite/spec/db/stash_datacite/affiliation_spec.rb
stash_engine/lib/stash/organization/ror.rb

Fixes the issue with fee waivers not working (https://github.com/CDL-Dryad/dryad-product-roadmap/issues/291). The primary issue was a difference between `country[:name]` (previously used in the code and tests) and `country['country_name']` (the actual structure returned by ROR).
Fixes the secondary display issue on the review page by surfacing the `affiliation.country_name`. (And this also simplifies the logic for `fee_waivered?`)

Fix fee waiver bug

---

stash_engine/app/models/stash_engine/url_validator.rb
stash_engine/lib/stash/url_translator.rb
stash_engine/spec/unit/stash/url_translator_spec.rb

For issue: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/279
- Stopped transforming Google drive share links (still need to translate for Docs, Sheets and Presentations) ... @sfisher I'm not certain if this will work in all situations
- Updated download URL format for Box

Fixed some issues with url translators

---

stash_datacite/app/views/stash_datacite/licenses/_review.html.erb

For: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/268
Broke license and terms of service agreement into two checkboxes on the 'Review and Submit' page.

broke up license and ToS on review page into 2 separate checkboxes

---

stash_engine/lib/tasks/stash_engine_tasks.rake

Update rake task to submit the records to Solr after updating their publication name.
@ryscher it doesn't look like the journal names were added to the migrated datasets. This PR contains a rake task that can be used to backfill that information (will do a Crossref API lookup for any publicationISSNs without a corresponding publicationName).
Alternatively you can also add an additional API call to your process to add it manually if you are already able to get it from the old system. I'm not super familiar with the API but it looks like this would work: `# post /datasets/<id>/set_internal_datum` with `{ data_type: 'publicationName', value: 'Some journal' }`

Journal backfill for DB and Solr

---

stash_engine/app/models/stash_engine/url_validator.rb
stash_engine/lib/stash/url_translator.rb
stash_engine/spec/unit/stash/url_translator_spec.rb
stash_engine/spec/unit/stash_engine/url_validator_spec.rb

reverted recent change to google url_translator that was accepting the html viewer version of google drive documents.
Updated url_validator to fix issue with google drive returning an HTTP 500 instead of 503. Will now attempt to follow the redirection for any HTTP status >= 500 with a redirect Location of for 'googleusercontent.com'
updated tests

Revert google url translators

---

stash_engine/app/helpers/stash_engine/admin_datasets_helper.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/views/stash_engine/admin_datasets/_curation_activity_form.html.erb

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/305
Updated `resource.curatable?` logic to allow embargoed resources to have their status changed to 'curation', 'withdrawn' or 'published'
Do we need to think about other ramifications @sfisher? For example if something is embargoed and changed to withdrawn or curation do we need to pull it from Solr?

Updated resource.curatable to allow embargoed to have status changes

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/controllers/stash_engine/metadata_entry_pages_controller.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/admin_datasets/curation_activity_change.js.erb

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/306
- Updated the Resource model's init logic to use the `current_editor_id` instead of `user_id`
- Updated the Admin page to set the `current_editor_id` to the current_user when changing status
- Updated the Admin page 'Last modified by' column to use the `editor`
- Fixed an issue where changing the status to 'Curation' was not displaying the 'edit metadata' pencil icon

Fix for bug in curation_activity user (curator vs owner of the resource)

---

stash-merritt/lib/stash/merritt/submission_job.rb

I was re-processing an item that had originally received an error during Merritt processing. It received this new error:
NoMethodError: undefined method `enqueued?` for "enqueued"::String
/apps/dryad/apps/ui/releases/stash/stash-merritt/lib/stash/merritt/submission_job.rb:28:in `submit!`
This change should fix the issue.

Change test for enqueued

---

stash_engine/app/models/stash_engine/identifier.rb

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/314
Added a new scope to the Identifier model to return datasets that are either published/embargoed and have a pubmedID in their internal datum
Goes with corresponding PR in the dryad repo which contains XML.ERB files and a new Rake task file.

New scope to support LinkOut

---

stash_api/app/controllers/stash_api/submission_queue_controller.rb
stash_api/config/routes.rb

This PR involves one on both dryad and stash repositories (copying and pasting description into both).
This is for our migration so as not to overwhelm things.  You can make a call to /api/queue_length with all the usual API headers, etc.
It will allow monitoring of queue length so as not to keep sending more stuff to the server if it already has a lot in queue (or it is being held for shutdown).  It returns the `queue_length` & `executor_queue_length`.
Generally speaking the executor queue length is about double (or sometimes a little more) the things that are actually queued for work to be done since the success/error callbacks also get put on the executor queue separately by the internals of the gem.
I'd probably do something like this (in pseudocode) and tune it if it either creates …

Api queue info

---

stash_api/app/controllers/stash_api/curation_activity_controller.rb

Part of https://github.com/CDL-Dryad/dryad-product-roadmap/issues/55
In the API, when adding a curation activity is of type 'published' or 'embargoed', do not overwrite an existing publication date. Once an item already has a publication date, it should not be changed by subsequent curation notes.
To test manually, use the API to create multiple curation activities of type 'published'. The date associated with the first-created curation activity should remain as the publication date of the resource.
(A request test is included in the dryad repo, https://github.com/CDL-Dryad/dryad/pull/105)

Retain the original publication date

---

stash_engine/app/controllers/stash_engine/landing_controller.rb

I think this only triggers in cases when the status gets delayed from our queue and the notification from Merritt comes in faster, so harder to test since it's based on timing.
This is the method at https://github.com/CDL-Dryad/stash/blob/master/stash_engine/lib/stash/repo/repository.rb around line 111.

Use the method on the class, not the instance

---

stash_api/app/controllers/stash_api/curation_activity_controller.rb

For ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/338
This is somewhat specialized functionality for migration, so I'm not adding new response tests. (There are already response tests that test the primary addition of curation activities.)
To test, submit a curation activity through the API with status `embargoed`, and include an explicit PublicationDate. The call should look something like this:
```curl --data "@/tmp/prov.json" -i -X POST https://dryad-dev.cdlib.org/api/datasets/doi%3A10.5061%2Fdryad.30cn0/curation_activity -H "Authorization: Bearer ab9e32b3c6b76cbc58a5c65fe113e9ca2ca6269770f45cbba753a5c457b79f53" -H "Content-Type: application/json" -o curlout.txt```
With a prov.json that looks like this:
```{"status":"embargoed","note":"Setting package-level embargo …
```

Handle PublicationDate that is explicitly set in a curation activity

---

stash_engine/app/mailers/stash_engine/user_mailer.rb
stash_engine/app/views/stash_engine/status_dashboard/show.html.erb

added the appropriate 'to' email address for dependency check failures
Also updated the text on the status_dashboard page from 'yellow' to 'orange' (orange was in our color palette)

Discovered a bug in the status dashboard. 

---

stash_engine/app/views/stash_engine/admin_datasets/activity_log.html.erb

Handle the rare case when someone is viewing the curation activities page, but the identifier's latest_resource has not yet been set.

Prevent null pointer exception when displaying curation activities

---

stash_api/app/controllers/stash_api/application_controller.rb
stash_api/app/controllers/stash_api/datasets_controller.rb
stash_api/app/controllers/stash_api/general_controller.rb
stash_api/app/models/stash_api/dataset.rb
stash_api/spec/unit/models/stash_api/dataset_spec.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/spec/db/stash_engine/identifier_spec.rb

This is for the first part of the ticket at https://github.com/CDL-Dryad/dryad-product-roadmap/issues/301  (basically the parts I've checked).  It's a PR across both Dryad and Stash repos.
The ticket describes it pretty well.
Mainly, any calls for generating dataset display structure for the API (Dataset.new) needs to take a user (or nil for public) because the dataset by default displays the latest version of the metadata that is available for viewing.  Different users will see different latest versions based on their ownership or roles vs the public.
The latest_viewable_resource takes care of most of this, but I needed to be sure the Dataset.new display setup was taking the user so it would calculate the display right.  Also had to change tests and add tests for it, which took some …

Api security part 1

---

stash_api/app/controllers/stash_api/datasets_controller.rb

This is part of this ticket.  https://github.com/CDL-Dryad/dryad-product-roadmap/issues/301   I'm doing some testing that changes to security keep these API calls working.  This is mostly testing with only a few code changes this time, but lots of tests.  Both in the Dryad and Stash repos.
The actions I'm testing:
- PATCH as a submission by setting the dataset status.
- PUT to replace the metadata with another set of metadata.
- PUT to "upsert" a new dataset which means insert a specific identifier and update the metadata at the same time (something we added for Dryad).
I'm trying to just do some sanity checks that these main endpoints work and they have appropriate security based on the API user, their role, etc.  There is a lot of duplication across them since they use the same security …

PUT/PATCH for API for a Dataset

---

stash_api/app/controllers/stash_api/versions_controller.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/spec/db/stash_engine/resource_spec.rb

This applies to both Dryad and stash repos. https://github.com/CDL-Dryad/dryad-product-roadmap/issues/363  .  It puts security for user/role on all versions endpoints with tests.  I also needed to update the download to use the streaming download instead of redirecting the versions download to Merritt.

Versions API Security

---

stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/lib/stash/payments/invoicer.rb
stash_engine/spec/db/stash_engine/curation_activity_spec.rb
stash_engine/spec/db/stash_engine/identifier_spec.rb
stash_engine/spec/unit/stash/payments/invoicer_spec.rb

When a dataset is published, and the associated journal is paying, add an "InvoiceItem" to their Stripe account. See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/235
To test (on dryad-dev):
- Create a new dataset
- Select "Manuscript in Progress"
- Enter the journal name "The American Naturalist" (this is the only journal currently set up in Stripe)
- Complete the submission, verifying that the review page states that the journal will pay
- Go to the Admin page, and find the dataset
- Change its status to "published"
- Verify that the journal has been invoiced, either by viewing the journal's customer page in Stripe, or by viewing the database field `stash_engine_identifiers.invoice_id`

Journal invoicing

---

stash_engine/db/migrate/20190715204229_add_index_to_stash_engine_internal_data.rb

Related to: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/359
@sfisher I manually added an index to the InternalDatum table on the migration server to address some issues we discovered while you were on vacation. I just remembered that I had not added a formal PR for the migration.

added index to stash_engine_internal_data.identifier_id

---

stash_engine/app/views/stash_engine/pages/home.html.erb

Just noticed that the link in the grey box on the homepage was not sending users to the membership info, so this patch just updates the href.

Updated link on homepage to point to membership info

---

stash_api/public/api/docs/index.html
stash_api/public/openapi.yml

These are the updates for this task.  https://github.com/CDL-Dryad/dryad-product-roadmap/issues/99
You can view the updated documentation at https://dryad-dev.cdlib.org/api/docs/ .
I changed the basepath to /api/v2 in the path since I think maybe that is what we'll use later, but it's something else we need to do (change the path) and agree on before release.
I also added some javascript to force changing the URL so it has a slash at the end since the OpenAPI JS viewer thing didn't work right without the trailing slash.

OpenAPI documentation updates

---

stash_engine/app/models/stash_engine/counter_citation.rb
stash_engine/app/models/stash_engine/counter_stat.rb
stash_engine/app/views/stash_engine/landing/_metrics.html.erb
stash_engine/lib/stash/event_data.rb
stash_engine/lib/stash/event_data/citations.rb
stash_engine/lib/stash/event_data/usage.rb
stash_engine/spec/data/event-data-citations1.json
stash_engine/spec/data/event-data-citations2.json
stash_engine/spec/data/mdc-usage.json
stash_engine/spec/unit/stash/event_data/citations_spec.rb
stash_engine/spec/unit/stash/event_data/usage_spec.rb

see https://github.com/CDL-Dryad/dryad-product-roadmap/issues/273 .
I optimized the way we obtain counter stats so it is more efficient.  The main problem, though, was the crossref events service doesn't return results and times out.  We started using DataCite's event service.  Also set up to get only the kinds of citations Martin said.
You can check that they show up in the UI by going to https://dryad-dev.cdlib.org/stash/dataset/doi:10.6071/m3rp49 and looking at the metrics.  It's deployed to dev on the development branch.  This dataset had its doi changed to be one that has citations and usage for your viewing pleasure.

This fixes display problems with the counter stats & some optimizations

---

stash_engine/lib/tasks/stash_engine_tasks.rake

Both of publish and embargo rake tasks were referencing the resource's most recent curation activity incorrectly. Looks like we forgot to update the tasks after changing the model

Fix for the publish and embargo rake tasks

---

stash_datacite/app/views/stash_datacite/resources/_review.html.erb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/spec/db/stash_engine/identifier_spec.rb

Addresses https://github.com/CDL-Dryad/dryad-product-roadmap/issues/207
To test, create a submission and go to the review page. If the submission is associated with a journal that allows review, or if it is not associated with a journal, the "private for peer review" section will be displayed. If it is associated with a journal that does not allow review, the "private for peer review" section will not display.
Journals that *don't* allow peer review include:
- The American Naturalist
- BioMed Research International
Journals that *do* allow peer review include:
- American Journal of Botany
- Biology Letters

Journal peer review

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/views/stash_engine/admin_datasets/index.html.erb

This is a bandaid to address the Gateway timeouts we started seeing when loading the admin curation page on the fully migrated DB.
I restricted the default view to only include datasets who are in 'Curation', 'Submitted' or 'Author Action Required' states.
For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/412

Added restriction to the default query behind the admin curation page

---

stash_datacite/app/controllers/stash_datacite/metadata_entry_pages_controller.rb
stash_datacite/app/controllers/stash_datacite/publications_controller.rb
stash_datacite/app/views/stash_datacite/metadata_entry_pages/_publication.html.erb
stash_datacite/lib/stash/import/crossref.rb
stash_datacite/lib/stash/indexer/indexing_resource.rb
stash_datacite/lib/tasks/publication_updater.rake
stash_datacite/lib/tasks/stash_datacite_tasks.rake
stash_datacite/spec/db/stash_datacite/author_spec.rb
stash_datacite/spec/db/stash_engine/proposed_change_spec.rb
stash_datacite/spec/unit/stash/import/crossref_spec.rb
stash_datacite/spec/unit/stash/indexer/indexing_resource_spec.rb
stash_engine/app/controllers/stash_engine/widgets_controller.rb
stash_engine/app/helpers/stash_engine/link_generator.rb
stash_engine/app/helpers/stash_engine/publication_updater_helper.rb
stash_engine/app/models/stash_engine/internal_datum.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/services/stash_engine/status_dashboard/oai_service.rb
stash_engine/app/views/stash_engine/publication_updater/_proposed_change_line.html.erb
stash_engine/lib/tasks/link_out.rake
stash_engine/spec/db/stash_engine/internal_datum_spec.rb

Moved the publication DOI data from `stash_engine_internal_data` to `dcs_related_identifiers`
For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/303
This also includes an update to the Publication Updater's OAI check to use a different URL per the Merritt team's request

Move publication DOI from InternalDatum to RelatedIdentifier

---

stash_api/app/controllers/stash_api/datasets_controller.rb

To support https://github.com/CDL-Dryad/dryad-product-roadmap/issues/236, allow selection of a dataset by manuscriptNumber. Note that the `publicationISSN` and `manuscriptNumber` may not be specified at the same time. 
To test, ensure  an dataset contains the target manuscript number, then make a GET call like: 
`curl -i -X GET http://ryandash.datadryad.org/api/datasets?manuscriptNumber=JAMIO-2017-0039.R2 -H "Authorization: Bearer 0dd1ce438bfb00c5101c466f6e3fc2a9cd4862f2495ce62953cbfb6d7ef10c74" -H "Content-Type: application/json" `

Allow API to find datasets by manuscript number

---

stash_engine/app/services/stash_engine/status_dashboard/dependency_checker_service.rb
stash_engine/app/services/stash_engine/status_dashboard/download_service.rb
stash_engine/app/services/stash_engine/status_dashboard/notifier_service.rb

This addresses some of the issues we've been seeing with the status dashboard checks: ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/414
- The OAI feed issue was resolved in a prior PR ... we updated the URL we were pinging.
- The Merritt download service has been reporting a 401 on the stage instance. I have updated the code to provide more information for us on the dashboard (basically the HTTP status) to help us debug. I think this may be a legit issue, it uses the following line, `client = Stash::Repo::HttpClient.new(tenant: resource.tenant, cert_file: APP_CONFIG.ssl_cert_file).client`, which references an SSL cert, so maybe something we need to update in the config files for the new linux2 servers
- Updated the Notifier service check to examine its cron log and …

Fix external dependency status checks

---

stash_engine/app/views/stash_engine/pages/_nav.html.erb
stash_engine/app/views/stash_engine/pages/_why_share.html.erb
stash_engine/app/views/stash_engine/pages/best_practices.html.erb
stash_engine/app/views/stash_engine/pages/our_staff.html.erb
stash_engine/app/views/stash_engine/sessions/_login_info.html.erb
stash_engine/app/views/stash_engine/user_mailer/submitted.html.erb

Per slack conversation w/ @dlowenberg:
1. In the email that goes to the author saying the process has begun (sorry for blanking which one it is) can you make sure at the end there is a line that says "Should you have any further questions about metadata, embargoing, or DOIs, please contact help@datadryad.org". [This is the only time we are going to even let them know they can embargo
2. On the Login page we have those three things Dryad commits. Can it be re-worded to say the following:
Curation
All datasets are curated to ensure they are Findable, Accessible, Interoperable, and Reusable
Compliance
Enabling adherence to funder and publisher open data mandates
Community Support
Dryad is researcher-led and supported by our institutional and publisher members
3. On the homepage where we have …

Some minor static content changes

---

stash_datacite/app/views/stash_datacite/licenses/_review.html.erb
stash_engine/app/mailers/stash_engine/user_mailer.rb
stash_engine/app/models/stash_engine/curation_activity.rb

Simplify the functionality for large file fees (https://github.com/CDL-Dryad/dryad-product-roadmap/issues/198)
- removes the automatic email to the helpdesk
- changes the warning box to a simpler paragraph
Note: automatic invoicing of large file fees will be added in a later PR.

Remove warning and email for large file fees

---

stash_engine/app/views/stash_engine/landing/_files_embargoed.html.erb

Test example on dev.
It was barfing out errors because someone used the wrong field name in the template.  See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/409

Fix the embargoed landing page

---

stash_engine/lib/tasks/migration.rake

I guess because that Gem isn't loaded in all environments and it affects rake tasks.

Having a byebug in there makes the capistrano deploy poop out in the middle

---

stash_engine/Gemfile.lock
stash_engine/stash_engine.gemspec

Another fix because capistrano hooks into rake and picking up dependency there even though this file isn't used for deploy.

gemfile changes for database_cleaner for capistrano

---

stash-notifier/config/notifier.yml

These are simple changes to set up the notifier, which we'll use in production.  For now this is being run against the migration environment with just the dryad collection.  When we go live, we should disable the migration environment and use the production one to notify.
Until release we don't really want to run this against production since it includes sets/collections that are currently being notified to existing Dash from the harvester script.  Those notifications will fail in Dryad since those items will not exist in our database until they are migrated from Dash.

Update prod notifier

---

stash_engine/app/models/stash_engine/resource.rb

For some reason, the affiliation method is not always added on my testing server. So I'm adding this patch until we rewrite the associated code to not use `user.affiliation`

Adding the author patch again

---

stash_engine/lib/tasks/counter.rake
stash_engine/lib/tasks/counter/log_combiner.rb
stash_engine/lib/tasks/counter/validate_file.rb

This is for github numbers 389 and 228 to work through the MDC/Counter logs.
- Counter rake tasks to scp & combine log files from all servers (so we can process them from the processor) and remove old logs.
- A validator to check the basic format of counter logs to be sure they seem valid since there were some problems with ones Ryan had originally.
These will eventually be added to the log with the Python script to cron processing daily.
1. combine log files
2. run python script to generate and submit (once we're in production) stats from combined daily logs.
3. delete old logs per our privacy policy.
I'll do a separate PR for actually putting it in the cron once I've tested it working on the server and it only runs in production environment.

Rake tasks for MDC log combining functions & log validation task

---

stash_engine/app/models/stash_engine/curation_activity.rb

Found an error when sorting the curation  table on  'Status' and one of the records has a nil status

added nil check for readable_status

---

stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb
stash_engine/app/models/stash_engine/admin_datasets/curation_table_row.rb
stash_engine/app/models/stash_engine/user.rb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb
stash_engine/app/views/stash_engine/admin_datasets/_filter.html.erb
stash_engine/app/views/stash_engine/admin_datasets/index.csv.erb
stash_engine/app/views/stash_engine/admin_datasets/index.html.erb

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/415
- Created new `StashEngine::AdminDatasets::CurationTableRow` model. It is not a normal active record model and does not persist data to the DB. It handles the SQL Query (search, filter, sort) and provides access to elements of Resource, Identifier, InternalDatum, ResourceState, CurationActivity, Authors, User in one model.
- Updated the ERBs used to display the data to work with the new model
- Removed all of the `build_table` code from the controller and updated it to use the new model
- The Author column on the page now lists ALL author last names instead of just the first one. 
- Updated the search logic to do a SQL `MATCH` and a `LIKE` against the title
- Updated the table to display a 'No records found' message …

Update to query behind the Curation page

---

stash_engine/app/controllers/stash_engine/publication_updater_controller.rb
stash_engine/app/helpers/stash_engine/publication_updater_helper.rb
stash_engine/app/views/stash_engine/publication_updater/index.html.erb

For tickets: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/412 and https://github.com/CDL-Dryad/dryad-product-roadmap/issues/427
- Fixed bug that was referencing the wrong field name in pub updater helper
- Fixed typos in sort names
- Tweaked load order so that it only loads the latest_resource data for the records that will be displayed on the page (after kaminari)

Fixes for the publication updater page

---

stash_datacite/lib/tasks/publication_updater.rake

For ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/430
- Updated code to do a direct SQL query since it needs to get at the latest resource and latest curation activity
- Updated criteria to only process datasets that are not 'in_progress', 'published' or 'embargoed' and whose latest curation activity occurred in the past 6 months (and does not already have accepted Crossref changes).
I already ran the changes against the stage DB so you can check out the Admin page to see the records it matched

updated publication updater to be more efficient

---

stash_engine/app/views/stash_engine/landing/_orcid_invite.html.erb

This "button" (actually link) was failing with an invalid path.  Changing to a POST fixes it since that is the way omniauth requires the route to be.
Fix for this ticket. https://github.com/CDL-Dryad/dryad-product-roadmap/issues/442

ORCID omniauth starting URL needs to be a POST, not a GET

---

stash_engine/db/migrate/20190906084410_change_value_to_long_text_on_stash_engine_external_references.rb
stash_engine/lib/stash/link_out/helper.rb
stash_engine/lib/stash/link_out/pubmed_sequence_service.rb
stash_engine/lib/stash/link_out/pubmed_service.rb
stash_engine/lib/tasks/link_out.rake

- Discovered that some of the datasets were blowing out the MySQL TEXT field size on the `stash_engine_external_reference` table that stores the GenBank sequence ids! So converting the field to LONGTEXT (one dataset on stage had over 100k sequences 😱 .
- Updated the DTD location and enabled the DTD validation code (the old linkout DTD did not validate)
- Added rescue block so that the Genbank Sequence will continue on if one of the records causes an error

Updates for LinkOut file generation

---

stash_engine/lib/stash/link_out/pubmed_service.rb

Nokogiri (and most XML libraries) automatically encode ampersand characters to prevent them from making the XML invalid. The LinkOut team wants the unencoded version though in the PubMed file.
Added a post-XML function that decodes it from `&amp;` back to `&`

updated link_out to reverse default ampersand encoding by Nokogiri

---

stash_datacite/app/models/stash_datacite/proposed_change.rb
stash_datacite/lib/stash/import/crossref.rb
stash_engine/app/views/stash_engine/publication_updater/_proposed_metadata.html.erb

Curators asked for the following changes to the Publication Updater screen:
1) the proposed publication date should never overwrite the dataset publication date because the proposed publication date is the 'Journal' publication date
2) the proposed authors should never overwrite the existing authors.
Removed the code that was including those data elements from the update and also updated the UI to no longer display those elements with a blue background and arrow

Tweak pub updater

---

stash_engine/spec/config/app_config.yml

Update the name to point to the long-term production server, rather than the "api" address which may be rerouted.

Update the name of "old" Dryad

---

stash_engine/app/models/stash_engine/resource.rb
stash_engine/lib/tasks/stash_engine_tasks.rake
stash_engine/spec/db/stash_engine/resource_spec.rb

The embargo updater was being bad and publishing anything with a publication date, whether it had been submitted to Merritt or whether the curation state was embargoed.  See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/455 .
🗞 🐕

Fix embargo updater so that it does the right thing

---

stash_datacite/app/views/stash_datacite/metadata_entry_pages/_code_for_geolocation_disabled.html.erb
stash_datacite/app/views/stash_datacite/metadata_entry_pages/_metadata_entry_form.html.erb
stash_datacite/app/views/stash_datacite/peer_review/_review.html.erb
stash_engine/app/models/stash_engine/noid_state.rb
stash_engine/app/views/stash_engine/dashboard/_migrate_alert.html.erb
stash_engine/app/views/stash_engine/file_uploads/_choose_upload_method.html.erb
stash_engine/app/views/stash_engine/pages/_why_use.html.erb
stash_engine/app/views/stash_engine/pages/home.html.erb
stash_engine/app/views/stash_engine/shared/_footer.html.erb
stash_engine/spec/unit/models/noid_state_spec.rb

This just adds a digit by default to the minter so it's 9 digits long.  I saw while running counter stats over the weekend that Dryad has some that are 8 digits long even though they said that 7 digits was their longest.  This is to prevent DOI collisions with any existing items.

Adding a digit to the NOID minter default to make it 9 digits.

---

stash_datacite/app/controllers/stash_datacite/publications_controller.rb
stash_datacite/lib/stash/indexer/indexing_resource.rb

We've gotten some notifications of internal errors when a user fails to enter the journal and/or msid, but presses the "Import Metadata" button. This prevents the errors.
(Also corrects some silly rubocop things)

Guard against an error when the msid (or journal name) is not provided

---

stash_datacite/app/controllers/stash_datacite/publications_controller.rb
stash_datacite/app/views/stash_datacite/resources/_in_progress_line.html.erb
stash_engine/app/models/stash_engine/author.rb

@briri or @ryscher maybe one of you can take a look at this in the morning since you'll likely be in earlier than me.
Mostly fixing nil errors we got emailed about and were repeated.
The other error is that's a bad idea to include '.first' in an activerecord scope because scopes are meant to be chained so they should return a result set (ActiveRecord Relation) and not a single item.  I believe when that single item returns nil then it returns an ActiveRecord relation without eliminating any records.  I think this is intentional, but kind of confusing.  Change this scope into a method instead.
These occurred while curators will trying to publish items that didn't have any primary authors for the stripe case (the nil).  The message about identifiers was a red herring I believe. …

Fixes curation errors because of strip & misc nil errors

---

stash_engine/lib/stash/link_out/helper.rb
stash_engine/lib/tasks/link_out.rake

- Moved the `sleep(1)` on the 2 link out seed tasks to the top of the loop. We were not sleeping when the pubmed api did not return anything.
- Added a `User-Agent` header to our requests to the PubMed api so that we're better citizens :)

Some minor tweaks to the LinkOut seed tasks

---

stash_engine/lib/stash/link_out/pubmed_service.rb

Our contact at PubMed asked that we remove the quotes from the callback urls portion of the linkup xml file.
She has manually corrected the file we generated today. This change will ensure that the quotes do not appear when the files are regenerated via cron (on Sundays)

removed quotes from part of pubmed linkout file

---

stash_engine/app/models/stash_engine/admin_datasets/curation_table_row.rb
stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb

INNER JOINING to identifier.  All imported Dash records have identifiers and all migrated Dryad content does.  Even if there is a resource without an identifier then it may not be curated because there will never be a landing page for it without a DOI.  We also have specifically excluded some resources by disconnecting them from their identifier so their landing page doesn't display or the version is excluded.
Added method to get resource for use in the curation page if it's needed (and caches it).  This will only load for items where it is used (one page full).
- If no identifier then no link to a landing page that cannot exist because an identifier is required for a landing page.
- The curators want to freely edit, so as long as it's submitted to Merritt they can edit.  Or they can go …

Fixing edit pencils and other enhancements and bugs

---

stash_datacite/lib/tasks/embargo_fix.rake

This script is messy, overly verbose, and has a hardcoded path. But it's a single-use script.
Given a list of DOIs, it fixes the issues of overly-conservative embargoes in items. It first verifies that an embargo was set by the migration process. It then cycles through the curation activities, and once an item was published in DSpace ("made available in DSpace"), it sets subsequent curation activities to status `published`, and deletes erroneous comments from the embargo checker ("publiction date has not yet been reached").

Add fixes for conservative embargoes

---

stash_engine/lib/tasks/file_path_hack.rake

I'll run this occasionally to be sure the temp_file_paths are still valid even after we do new releases.  This is just a temporary hack.
Thinking about it, it may be that temp_file_path may only be used on the file upload page for keeping track of where to write chunks of a file.  If so it is less severe of a problem and will probably only break people's uploads if they're in the middle of uploading while we do a new release.

This is a quick hack to update temp_file_paths to current

---

stash_datacite/.rubocop.yml
stash_datacite/lib/tasks/embargo_fix.rake
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/app/views/stash_engine/landing/_files.html.erb
stash_engine/spec/db/stash_engine/identifier_spec.rb

This was a bad interaction between suppressing versions and also overly complicated and unclear embargoing/publishing practices and versioning.
For now it assumes the last embargo/published state applies to all versions before it.
For the future we need to make this much more explicit and much less complicated.  We can address curators desire to hide versions they don't like at the same time.
The changes to ryan's migration script were rubocop autofixes but shouldn't change function.

Files disappearing fix for individual file/version downloads

---

stash_datacite/lib/tasks/embargo_fix.rake
stash_engine/lib/tasks/stash_engine_tasks.rake

An extension of #277, using almost the exact same logic, but to correct the work of the "Embargo Datasets CRON".
Note, this has already been run on production, so it shouldn't need to run again, but I wanted to save the code so we can reference it later if needed.

Correct over-zealous use of the Embargo Datasets CRON

---

stash_engine/lib/stash/payments/invoicer.rb
stash_engine/spec/unit/stash/payments/invoicer_spec.rb

For https://github.com/CDL-Dryad/dryad-product-roadmap/issues/510
Corrects some issues with the Stripe invoices:
- set the `auto_advance` property using the correct mechanism
- force invoices to be emailed using `send_invoice` instead of `finalize_invoice`
- put the customer's name in `Customer.name` instead of description
Unfortunately, since Stripe's testmode doesn't send email, the only way to truly test this is to create real invoices, and then go into Stripe and void them. I have done this, but boo to Stripe.

Invoicer auto advance

---

stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/models/stash_engine/resource.rb
stash_engine/db/migrate/20190926213516_add_public_view_to_resources.rb
stash_engine/db/migrate/20190926214109_add_pub_state_to_identifier.rb
stash_engine/lib/tasks/versioning.rake
stash_engine/spec/db/stash_engine/curation_activity_spec.rb
stash_engine/spec/db/stash_engine/identifier_spec.rb
stash_engine/spec/db_spec_helper.rb

This is the PR for https://github.com/CDL-Dryad/dryad-product-roadmap/issues/525 .
Essentially, we have flags for a couple things at the resource level and an overall status at the dataset level indicating the current status.  All of this will simplify creating views from overly-complex queries for a standard public view and also allow us to override what is viewed by the public if we wish without having to resort to ugly database hacks like orphaning resources.
Added pub_state to identifier level, which summarizes the status the public sees.
Added meta_view and file_view flags to indicate what resources the public could see.
Embargo is meta_view=true and file_view=false for a resource.  Published=meta_view=true and file_view=true.
We know the latest metadata to display from the last …

Populating and calculating view for submitted versions

---

stash_engine/app/mailers/stash_engine/user_mailer.rb
stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/views/stash_engine/user_mailer/journal_published_notice.html.erb
stash_engine/spec/db/stash_engine/curation_activity_spec.rb
stash_engine/spec/db/stash_engine/identifier_spec.rb

PR in stash and dryad-config for CDL-Dryad/dryad-product-roadmap#506
When a dataset is set to status `embargoed` or `published`, email a notice to any associated journal, but only if this is the first time the dataset has been embargoed or published. (We don't want to send multiple notices to the journals when there are new versions or curation weirdness.)

Journal published notice

---

stash_engine/lib/stash/link_out/pubmed_sequence_service.rb
stash_engine/lib/stash/link_out/pubmed_service.rb

Added api key to calls to NIH for pubmed and genbank id searches. https://www.ncbi.nlm.nih.gov/books/NBK25497/
Everything seems to be working properly still with the api keys in place when I run the rake seed tasks locally.

Adding NIH API key for Link out

---

stash_engine/lib/stash/link_out/pubmed_service.rb

Link Out team noted an issue with an ampersand character in one of the files. This was working until we were also asked to remove quote characters from the same section of that file. This caused the `gsub` to no longer properly deal with the ampersand.

Link out fix

---

stash_datacite/app/views/stash_datacite/resources/_submitted_line.html.erb

For https://github.com/CDL-Dryad/dryad-product-roadmap/issues/546
On the user dashboard, this adds a "Preview" link for items  in the "Submitted" section.

Add "Preview" link to user dashboard.

---

stash_engine/app/models/stash_engine/identifier.rb
stash_engine/app/views/stash_engine/landing/_files_embargoed.html.erb
stash_engine/app/views/stash_engine/user_mailer/embargoed.html.erb
stash_engine/spec/db/stash_engine/identifier_spec.rb
stash_engine/spec/unit/mailers/user_mailer_spec.rb

For https://github.com/CDL-Dryad/dryad-product-roadmap/issues/505
When a dataset is put into `embargoed` status, and the curation activities indicate that the embargo is dependent on the publication of an associated article, indicate this in two ways:
- different text on the landing page (where the download links would normally appear)
- additional text in the confirmation email that goes to the submitter

Differentiate embargoes for that are dependent or article publication

---

stash_engine/app/controllers/stash_engine/downloads_controller.rb
stash_engine/app/controllers/stash_engine/shared_security_controller.rb

We had an error that happens only with large files and a sharing link.  Simple fix and most of this PR is in testing which was a pain, see both stash and dryad repos.
Also minor change to be sure admin? security lookup it handles nils gracefully.  I think it should already, but just in case.

Fix for asynchronous download while using a sharing link

---

stash_engine/app/models/stash_engine/curation_activity.rb

Part of https://github.com/CDL-Dryad/dryad-product-roadmap/issues/545
In some cases, curators were able to issue two invoices for the same item. Ensure the Identifier object is up to date before checking whether it has an invoice_id.

Protect against duplicate invoicing

---

stash_engine/lib/stash/download/base.rb

Follow up to 10 redirects because Merritt really likes to give a lot (at least 5 or 6) in some cases and it may cause download to fail for full version.
Critical when using the Merritt UI since it redirects millions of times before giving a download for a version.  I tested this on the server and it works.
I'll re-tag to include this since I discovered it from stage downloads.

A small change for following more redirects when downloading

---

stash_api/app/controllers/stash_api/curation_activity_controller.rb
stash_engine/app/models/stash_engine/curation_activity.rb
stash_engine/spec/unit/models/curation_activity_spec.rb

For https://github.com/CDL-Dryad/dryad-product-roadmap/issues/566
When a curation activity is submitted through the API, if it comes from the journal module, don't let it move the workflow backwards.
I originally tried to add this to the Curation Activity model, for ease of testing, but I couldn't get it to work within the callbacks since it was changing the object.
We don't currently have automated tests that run through the email process. The process for manually testing issues with the email workflow is somewhat convoluted, so I added some documentation about the test process here: http://wiki.datadryad.org/Journal_Metadata_Processing_Technology#Testing_the_end-to-end_Workflow

Enforce workflow

---

stash_engine/app/controllers/stash_engine/file_uploads_controller.rb
stash_engine/app/models/stash_engine/file_upload.rb
stash_engine/spec/db/stash_engine/file_upload_spec.rb

I'm not sure how they're doing this, but I believe this will keep the deletion filename from appearing more than once.  See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/514

Keep people from double-deleting the same files

---

stash_engine/app/models/stash_engine/counter_stat.rb
stash_engine/spec/db/stash_engine/counter_stat_spec.rb
stash_engine/test/models/stash_engine/counter_stat_test.rb

A PR for part of ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/541 .
This gets the stats from DataCite again instead of just out of our database.  Changed caching to do per calendar week.  Added tests that didn't seem to exist for this class yet.

This allows us to pull Counter CoP stats back from DataCite with 1 week cache
